# Site settings
# in the templates available like {{ site.myvariable }}.
title: Blog cua Meo 
email: neko@hihi.com
brand: Neko
headline: Instagramer and Daydreamer 
description: > # this means to ignore newlines until "baseurl:"
  Blog cua Meo
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
copyright: 2016 Whatever Company, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: sbrina1995@gmail.com


# Tracking
googleAnalitycsID: UA-83933844-1

