# Site settings
# in the templates available like {{ site.myvariable }}.
title: Day la blog cua Neko
email: neko@hihi.com
brand: Neko
headline: Traveler and Cutest
description: > # this means to ignore newlines until "baseurl:"
  Day la blog moi tao cua Meo nha
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
copyright: 2016 Whatever Company, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: your.name@gmail.com
phone: +1-800-555-2016

# Tracking
googleAnalitycsID: UA-83933844-1

